Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -32,12 +32,24 @@ jobs:
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 2.1.x
+        
     - name: Restore dependencies
       run: dotnet restore apis/poi/poi.sln
+      
     - name: Build
       run: dotnet build --no-restore apis/poi/poi.sln
+      
     - name: Test
-      run: dotnet test --no-build --verbosity normal apis/poi/poi.sln      
+      run: dotnet test --no-build --verbosity normal -r testresults --logger "trx;logfilename=apipoi.trx" apis/poi/poi.sln
+      
+    - name: API POI Tests Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()  # run this step even if previous step failed
+      with:
+        name: API POI Tests       # Name of the check run which will be created
+        path: testresults/*.trx   #Path to test results
+        reporter: dotnet-trx      #Reporter      
+      
 #Opens An Issue Only When CI Fails
     - uses: actions/github-script@0.9.0
       if: failure()
